# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4f134e498b3059524c8fdb68828b0c738e7459986620eef530a9ba768278e2e556667a5370f0cf948ae8a811ece1383c2a748853d6d638e4dde1abd4b8bc0e4

test:
  secret_key_base: cd3d7091bc64561f20e879dfdfaf234eb72cf2c7199db39693a162af7c9d7106d86f28b7e3a06e56b5112e897c70ad960d223bc3739570717e0dba5c4f8ad10a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
